services:
  web:
    build: .
    ports:
      - "9999:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=parted
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - .:/app
    networks:
      - parted_network

  db:
    image: postgres:latest
    ports:
      - "9998:5432"
    environment:
      POSTGRES_DB: parted
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parted_network

volumes:
  postgres_data:

networks:
  parted_network:
    driver: bridge
