# Generated by Django 5.1.6 on 2025-04-04 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_genre_artist_genres_artist_main_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', related_query_name='artist', to='artist.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='main_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_artists', related_query_name='primary_artist', to='artist.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='artist_profiles', related_query_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
