# Generated by Django 5.1.6 on 2025-04-04 03:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_genres_alter_artist_main_genre_and_more'),
        ('user', '0005_alter_fanprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='ArtistProfile',
        ),
    ]
