# Generated by Django 5.1.6 on 2025-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_rename_artist_artistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
