# Generated by Django 5.1.6 on 2025-03-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_fanprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
