# Generated by Django 5.1.6 on 2025-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='fanprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
