# Generated by Django 5.1.6 on 2025-03-18 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_fanprofile_profile_image_alter_fanprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fan_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
